export const SIGNED_IN = "SIGNED_IN"
export const FETCH_SEARCH = "FETCH_SEARCH"
export const FETCH_POPULAR = "FETCH_POPULAR"
export const FETCH_GENRE = "FETCH_GENRE"
export const SET_REVIEWS = "SET_REVIEWS"
